# SwiftLint Configuration for JoyaFix
# Strict but reasonable rules for professional code quality

disabled_rules:
  - trailing_whitespace  # Disabled to avoid noise during migration
  - line_length          # Disabled to avoid noise during migration

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicit_return
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rules configuration
force_cast: warning
force_try: warning
function_body_length: 300
function_parameter_count: 8
identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - ok
    - x
    - y
    - z
nesting:
  type_level: 2
  function_level: 3
type_body_length: 500
type_name:
  min_length: 3
  max_length: 50

# File-level exclusions
excluded:
  - build
  - .build
  - JoyaFix.app
  - Tests

