# .swiftlint.yml מעודכן
disabled_rules:
  - trailing_whitespace
  - line_length
  - cyclomatic_complexity
  - file_length
  - type_body_length
  - function_body_length
  - large_tuple
  - multiple_closures_with_trailing_closure
  - force_unwrapping
  - todo

opt_in_rules:
  - empty_string
  - first_where
  - sorted_imports

# הפסקת חסימת הבנייה על אזהרות
warning_threshold: 1000

excluded:
  - build
  - .build
  - JoyaFix.app
  - Tests
