import SwiftUI
import Foundation

struct AboutView: View {
    @Environment(\.dismiss) var dismiss
    
    /// Fail-safe logo loading - tries multiple methods
    private func loadLogoImage() -> NSImage? {
        // Priority 1: Bundle.module (SPM development/testing)
        #if !os(iOS) // Bundle.module generated by SPM
        if let url = Bundle.module.url(forResource: "FLATLOGO", withExtension: "png"),
           let image = NSImage(contentsOf: url) {
            return image
        }
        #endif
        
        // Priority 2: Bundle.main (final app bundle)
        if let image = NSImage(named: "FLATLOGO") {
            return image
        }
        
        // Fallback: Try from bundle with path
        if let logoPath = Bundle.main.path(forResource: "FLATLOGO", ofType: "png"),
           let logoImage = NSImage(contentsOfFile: logoPath) {
            return logoImage
        }
        
        return nil
    }
    
    /// Gets changelog from version.json or returns nil
    private func getChangelog() -> String? {
        // Define UpdateInfo struct locally (matches UpdateManager.UpdateInfo)
        struct LocalUpdateInfo: Codable {
            let version: String
            let releaseNotes: String?
            let downloadURL: String?
            
            enum CodingKeys: String, CodingKey {
                case version
                case releaseNotes = "release_notes"
                case downloadURL = "downloadUrl"
            }
        }
        
        // Try to load from version.json in bundle
        if let versionURL = Bundle.main.url(forResource: "version", withExtension: "json"),
           let data = try? Data(contentsOf: versionURL),
           let versionInfo = try? JSONDecoder().decode(LocalUpdateInfo.self, from: data) {
            return versionInfo.releaseNotes
        }
        
        // Fallback: Try to load from app support directory (for updates)
        if let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first {
            let versionURL = appSupport.appendingPathComponent("JoyaFix/version.json")
            if FileManager.default.fileExists(atPath: versionURL.path),
               let data = try? Data(contentsOf: versionURL),
               let versionInfo = try? JSONDecoder().decode(LocalUpdateInfo.self, from: data) {
                return versionInfo.releaseNotes
            }
        }
        
        return nil
    }
    
    var body: some View {
        VStack(spacing: 24) {
            // App Icon - Fail-safe logo loading
            Group {
                // Try multiple methods to load logo (development and production)
                if let logoImage = loadLogoImage() {
                    Image(nsImage: logoImage)
                        .resizable()
                        .scaledToFit()
                        .frame(width: JoyaFixConstants.aboutLogoSize, height: JoyaFixConstants.aboutLogoSize)
                        .shadow(color: .black.opacity(0.2), radius: 10, x: 0, y: 5)
                } else {
                    // Fallback: System icon if logo not found
                    Image(systemName: "app.fill")
                        .font(.system(size: 80))
                        .foregroundColor(.blue)
                        .frame(width: 128, height: 128)
                }
            }
            
            // App Name
            Text(NSLocalizedString("about.app.name", comment: "App name"))
                .font(.system(size: 36, weight: .bold))
            
            // Version
            Text(String(format: NSLocalizedString("about.version", comment: "Version"), "1.0.0"))
                .font(.system(size: 14))
                .foregroundColor(.secondary)
            
            Divider()
                .padding(.horizontal, 40)
            
            // Credits
            VStack(spacing: 8) {
                Text(NSLocalizedString("about.created.by", comment: "Created by"))
                    .font(.system(size: 12))
                    .foregroundColor(.secondary)
                Text("Gal Sasson")
                    .font(.system(size: 16, weight: .semibold))
                
                Text(NSLocalizedString("about.powered.by", comment: "Powered by"))
                    .font(.system(size: 12))
                    .foregroundColor(.secondary)
                    .padding(.top, 8)
                Text("JoyaTech")
                    .font(.system(size: 16, weight: .semibold))
            }
            
            Divider()
                .padding(.horizontal, 40)
            
            // Features
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    // Current Features
                    VStack(alignment: .leading, spacing: 8) {
                        Text(NSLocalizedString("about.features", comment: "Features"))
                            .font(.system(size: 16, weight: .bold))
                            .padding(.bottom, 4)
                        
                        // Clipboard History
                        FeatureRow(icon: "clipboard", iconColor: .blue, text: "Clipboard History")
                        
                        // AI Text Enhancement
                        FeatureRow(icon: "sparkles", iconColor: .purple, text: "AI Text Enhancement (Gemini/OpenRouter)")
                        
                        // Keyboard Cleaner
                        FeatureRow(icon: "keyboard", iconColor: .red, text: "Keyboard Cleaner")
                        
                        // Caffeine Mode
                        FeatureRow(icon: "cup.and.saucer.fill", iconColor: .orange, text: "Caffeine Mode (Keep Awake)")
                        
                        // Color Picker
                        FeatureRow(icon: "eyedropper", iconColor: .cyan, text: "Color Picker")
                        
                        // Scratchpad
                        FeatureRow(icon: "note.text", iconColor: .yellow, text: "Quick Scratchpad")
                        
                        // Vision Lab
                        FeatureRow(icon: "eye", iconColor: .pink, text: "Vision Lab (Image-to-Prompt)")
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
            .frame(height: 250)
            
            Divider()
                .padding(.horizontal, 40)
            
            // What's New / Changelog
            if let changelog = getChangelog(), !changelog.isEmpty {
                VStack(alignment: .leading, spacing: 8) {
                    Text(NSLocalizedString("about.whats.new", comment: "What's New"))
                        .font(.system(size: 14, weight: .semibold))
                        .padding(.bottom, 4)
                    
                    ScrollView {
                        Text(changelog)
                            .font(.system(size: 12))
                            .foregroundColor(.secondary)
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .frame(height: 80)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                
                Divider()
                    .padding(.horizontal, 40)
            }
            
            // Copyright
            Text(NSLocalizedString("about.copyright", comment: "Copyright"))
                .font(.system(size: 11))
                .foregroundColor(.secondary)
            
            // Close Button
            Button(NSLocalizedString("about.close", comment: "Close button"), action: { dismiss() })
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
        }
        .padding(40)
        .frame(width: 500, height: 700)
    }
}

// MARK: - Feature Row

struct FeatureRow: View {
    let icon: String
    var iconColor: Color = .blue
    let text: String
    
    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.system(size: 14))
                .foregroundColor(iconColor)
                .frame(width: 20)
            Text(text)
                .font(.system(size: 13))
        }
        .padding(.vertical, 2)
    }
}

